config/routes.rb
Rails.application.routes.draw do
  resources :students do
    member do 
      get :generate_num
      get :student_description
      put :change_standard
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "students#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy generate_num change_standard]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render json: {}, status: :ok }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def generate_num
    @random_number = rand(100000..999999)
    puts "------------------ @random_number 1 #{@random_number}"
    respond_to do |format|
      format.html { redirect_to students_url}
      format.js { render :generate_num }
      # format.js { render layout: false, content_type: 'text/javascript' }
    end
    # respond_to :html, :js
  end

  def student_description
    @student = Student.find_by(id: params[:id])
    respond_to do |format|
      format.html { redirect_to students_url }
      format.js { render :student_description }
    end
  end

  def change_standard
    if @student.update(student_params)
      render json: { status: 'success', standard: @student.standard }
    else
      render json: { status: 'error' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :city, :email, :standard)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title StudentBlog
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = stylesheet_link_tag "bootstrap.min"
    = javascript_include_tag "application"
    = yield :css_code
    = yield :js_code
  %body
    = yield

app/views/students/_form.html.haml
= form_with(model: student) do |form|
  - if student.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(student.errors.count, "error")
        prohibited this student from being saved:
      %ul
        - student.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :name, style: "display: block"
    = form.text_field :name
  %div
    = form.label :city, style: "display: block"
    = form.text_field :city
  %div
    = form.label :email, style: "display: block"
    = form.text_field :email
  %div
    = form.submit

app/views/students/_otp_para.html.haml
- puts "------------------ random_number in partial #{random_number}"

= random_number

app/views/students/_stud_description.html.haml
%p
  student name is
  %b= student.name
  student is leaving in
  %b= student.city
  Student email is
  %b= student.email
  If you have any query or complaint for 
  %b= student.name
  please email on 
  %b= student.email 
  and if you want to direct contact then go to 
  %b= student.city

app/views/students/_student.html.haml
%div{:id => "#{dom_id student}"} 
  %table
    %thead
      %tr
        %th Name
        %th city
        %th email
        %th action
  %tbody
    %tr
      %td= student.name
      %td= student.city
      %td= student.email
      %td= link_to "Student description", student_description_student_path(student), remote: true
      %td= link_to "Show this student", student

app/views/students/edit.html.haml
%h1 Editing student
= render "form", student: @student
%br/
%div
  = link_to "Show this student", @student
  |
  = link_to "Back to students", students_path

app/views/students/generate_num.js.haml
- puts "-----------------------"
$("#otp").html("#{escape_javascript(render partial: 'otp_para', locals: { random_number: @random_number } )}");

app/views/students/index.html.haml
%div.container  
  %p{:style => "color: green"}= notice
  %h1 Students
  %table.table
    - standard_array = ["1","2","3","4","5","6","7","8","9","10"]
    - puts "#{standard_array}" 
    %thead
      %tr
        %th Id
        %th Name
        %th city
        %th email
        %th standard
        %th action
    %tbody
    - @students.each do |student|
      %tr
        %td= student.id
        %td= student.name
        %td= student.city
        %td= student.email
        %td
          - current_standard = student.standard
          - current_standard_index = standard_array.find_index(current_standard)
          %input.standard_change{value: student.standard, type: 'checkbox', checked: student.standard , data: {student_id: "#{student.id}"}} 
          %span= student.standard
          %span= current_standard_index + 1
        %td= link_to "Student description", student_description_student_path(student), remote: true
        %td= link_to "Show this student", student
      %br
  %br
  %div.container#stud_description
  = link_to "New student", new_student_path, class:"btn btn-primary"

- content_for :js_code do
  :javascript
    $(document).ready(function(){
      $(".standard_change").on("change", function(){
          student_id = $(this).attr("data-student-id") 
          console.log(student_id)
        
        $.ajax({
          url: "/students/"+ student_id +"/change_standard",
          data: {student: {standard: $(this).val()}},
          type: 'put',
          dataType: 'json',
          success: function(result){
            
          }
        })
      })
    })

app/views/students/new.html.haml
%h1 New student
= render "form", student: @student
%br/
%div
  = link_to "Back to students", students_path

app/views/students/show.html.haml
%p{:style => "color: green"}= notice
= render @student

%p#otp 1234

= link_to "generate no.", generate_num_student_path(@student), remote: true

%div
  = link_to "Edit this student", edit_student_path(@student)
  |
  = link_to "Back to students", students_path
  
  = button_to "Destroy this student", @student, method: :delete

app/views/students/student_description.js.haml
$("#stud_description").html("#{escape_javascript(render partial: 'stud_description', locals: { student: @student } )}");